config/routes.rb
AjCapital::Application.routes.draw do

  devise_for :users#, :controllers => { :registrations => :registrations }
  
  namespace :admin do
    resources :users
    resources :messages
    resources :documents
    get '/financials' => 'documents#financials'
    get '/reports' => 'documents#reports'
    get '/misc' => 'documents#misc'
  end

  root :to => 'site#index'
  match 'user_root' => 'messages#index'
  match '/portal' => 'messages#index', :via => :get
  match '/message/:id' => 'messages#show', :as => :message, :via => :get
  match '/message/:id/hide' => 'messages#hide', :as => :hide_message#, :via => :post
  
  match '/documents' => 'documents#index', :via => :get 
  get '/documents/financials' => 'documents#financials'
  get '/documents/reports' => 'documents#reports'
  get '/documents/misc' => 'documents#misc'
  get '/download/:id' => 'documents#download',:as => :download
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, :polymorphic => true
  has_many :recipients, :class_name => 'MessageRecipient', 
                        :order => 'kind DESC, position ASC', 
                        :dependent => :destroy

  has_many :message_documents
  has_many :documents, :through => :message_documents

  validates :state, :presence => true
  validates :sender_id, :presence => true
  validates :sender_type, :presence => true

  attr_accessible :subject, :body, :to, :cc, :bcc, :sender_type, :sender_id, :type, :document_ids

  after_save :update_recipients

  
  default_scope order('created_at DESC')
  scope :visible, where( :hidden_at => nil )

  state_machine :state, :initial => :unsent do
    event :queue do
      transition :unsent => :queued, :if => :has_recipients?
    end

    event :deliver do
      transition [:unsent, :queued] => :sent, :if => :has_recipients?
    end
  end

  state_machine :hidden_at, :initial => :visible do

    event :hide do
      transition all => :hidden
    end

    event :unhide do
     transition all => :visible
    end

    state :visible, :value => nil
    state :hidden, :value => lambda {Time.now}, :if => lambda {|value| value}
  end



  def to(*receivers)
    receivers(receivers, 'to')
  end
  alias_method :to=, :to
  
  def cc(*receivers)
    receivers(receivers, 'cc')
  end
  alias_method :cc=, :cc
  
  def bcc(*receivers)
    receivers(receivers, 'bcc')
  end
  alias_method :bcc=, :bcc
  
  def forward
    message = self.class.new(:subject => subject, :body => body)
    message.sender = sender
    message
  end

  def reply
    message = self.class.new(:subject => subject, :body => body)
    message.sender = sender
    message.to(to)
    message
  end
  
  def reply_to_all
    message = reply
    message.cc(cc)
    message.bcc(bcc)
    message
  end

  # def attachments
  #   @attachments
  # end

  # def add_attachment(*files)
  #   @attachments = []
  #   files.each do |file|
  #     @attachments.push file
  #   end
  # end
  
  private
    # Create/destroy any receivers that were added/removed
    def update_recipients
      if @receivers
        @receivers.each do |kind, receivers|
          receivers = receivers.reject { |r| r.blank? }.map { |r| User.find(r) }

          kind_recipients    = recipients.select {|recipient| recipient.kind == kind}
          new_receivers      = receivers - kind_recipients.map(&:receiver)
          removed_recipients = kind_recipients.reject { |recipient| receivers.include?(recipient.receiver) }
          
          recipients.delete(*removed_recipients) if removed_recipients.any?

          new_receivers.each do |receiver| 
            self.recipients.create!(:receiver => receiver, :kind => kind)
          end
        end
        
        @receivers = nil
      end
    end

    
    # Does this message have any recipients on it?
    def has_recipients?
      (to + cc + bcc).any?
    end
    
    # Creates new receivers or gets the current receivers for the given kind (to, cc, or bcc)
    def receivers(receivers, kind)
      if receivers.any?
        (@receivers ||= {})[kind] = receivers.flatten.compact
      else
        @receivers && @receivers[kind] || recipients.select {|recipient| recipient.kind == kind}.map(&:receiver)
      end
    end
end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < ApplicationController
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #   IMPORTANT NOTE!
  # 
  #   The `load_and_authorize_resource` method automagically creates the instance 
  #   for each method below.
  # 
  #   They remain in place but commented out for the sake of being explicit
  # 
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  load_and_authorize_resource

  layout 'portal'

  def index
    @messages = @messages.where(state: 'sent').order("updated_at DESC").page(params[:page]).per(PER_PAGE)
  end

  def new
    @users = User.all
    @message = Message.new
  end

  def create
    if @message.save
      @message.deliver
      redirect_to portal_path, notice: 'Message successfully sent!'
    else
      redirect_to new_admin_message_path, notice: 'Something went wrong..'
    end
  end

  def edit
    @users = User.all
  end

  def update
    if @message.update_attributes(params[:message])
      redirect_to admin_messages_path, notice: 'Message was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    if @message.destroy
      redirect_to admin_messages_path, notice: 'Message was successfully deleted.'
    else
      redirect_to admin_messages_path, notice: 'Something went wrong..'
    end
  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_filter :authenticate_user!, :except => :index
  layout 'portal'

	def index
    if user_signed_in? && current_user
      redirect_to admin_messages_path if current_user.admin?
      
      rec_messages = current_user.received_messages.order("updated_at ASC")
      @received_messages = []
      rec_messages.each do |e|
        @received_messages << e.message
      end
    
      @messages = Kaminari.paginate_array(@received_messages).page(params[:page]).per(PER_PAGE)


    else
      redirect_to new_user_session_path
    end
	end

  def show

    @message = Message.find(params[:id])
    get_users_message_copy

    # mark users's message copy as read
    @recipient_copy.view
  end


  def hide
    # @message = Message.find(params[:id])
    get_users_message_copy


    if @recipient_copy.hide
      redirect_to portal_path, notice: 'Message has been archived!'
    else
      redirect_to portal_path, notice: 'Something went wrong!!'
    end
  end
	

  private

    def get_users_message_copy
      @recipient_copy = MessageRecipient.where(message_id: params[:id], receiver_id: current_user.id).first
    end
end

app/helpers/message_helper.rb
module MessageHelper 

  # Adds red dot with # of unread messages
  def unread_count
    "<span class='unread-count'>#{current_user.unread_messages_count}</span>".html_safe if current_user.unread_messages_count > 0
  end

  def attachment_indicator(msg)
    if msg.documents.length > 0
      "<i class='icon-paper-clip'></i>".html_safe 
    end
  end

  # Adds blue dot in message list
  def unread_indicator(msg)
      @msg = MessageRecipient.where(:message_id => msg.id, :receiver_id => current_user.id).first
      output = "<span class='unread'>#{icon_helper('icon-circle')}</span>".html_safe
      else_put = "<span class='read'>#{icon_helper('icon-circle')}</span>".html_safe
      # output if @msg.state == 'unread'
      @msg.state == 'unread' ? output : else_put
  end

  # Changes the label for the Submit button the Message form depending on the state of the record.
  def msg_button_label(msg)
    msg.new_record? ? 'Send Message' : 'Update Message'
  end

 


end

app/views/messages/index.html.erb
<% title 'Investor Portal' %>
<section id="portal">
  <header>
    <div class="content">
      Inbox
      <%= select_year(Date.today, :start_year => 2013, :end_year => Date.today.year) %>
      <span class="right"> Welcome  <%= current_user.email %> </span>
    </div>
  </header>

<ul class="messages">
  <% if @messages.empty? %>
       <li class="document">
        <ul>
          <li>Sorry, no messages found</li>
        </ul>
      </li>
  <% else %>
    <% @messages.each do |msg| %>
      <li class="user message" id="msg-<%= msg.id %> " data-year="<%= msg.created_at.strftime("%Y") %>">
        <ul>
          <li style="msg-unread"><%= unread_indicator(msg)%></li>
          <li class="msg-sender"><%= link_to  msg.sender.username, message_path(msg) %></li>
          <li class="msg-attachment"><%= attachment_indicator(msg) %> </li>
          <li class="msg-subject"> <%= link_to msg.subject, message_path(msg) %></li>
          <li class="msg-timestamp"> <%= msg.created_at.strftime("%B %d at %l:%M %P") %> </li>
          <li class="msg-controls">
            <%= link_to icon_helper('icon-remove') , hide_message_path(msg), class:'button delete' %>
          </li>
        </ul>
      </li>
    <% end %>
  <% end %>
</ul>
  <%= paginate @messages %>
</section>

app/views/messages/show.html.erb
<% title @message.subject %>
<section id="message-new">
  <header>
    <div class="content">
        View Message
    </div>
  </header>
  <div class="show-message">
    <div class="msg-head">
      <%= image_tag('ajcp-logo_small.png', :style => 'float: left; margin-right: 15px;')%>
      <div class="msg-from">From: <%= @message.sender.username %></div>
      <div class="msg-sent">Sent: <%= @message.created_at.strftime("%B %d %l:%M %P") %></div>
      <div class="msg-subject"><%= @message.subject %></div>
    </div>
    <div class='msg-body'>
      <%= simple_format @message.body %>
      
    </div>
    <div class='msg-attachments'>
      <% if @message.documents.length > 0 %> 
        Attachments:<br>  
        <% @message.documents.each do |doc| %>
          <%= link_to icon_helper('icon-file-alt') + "  #{doc.title}<br>".html_safe, download_path(doc) %>
        <% end %>
      <% end %>
    </div>

  </div>
</section>