config/routes.rb
AjCapital::Application.routes.draw do

  devise_for :users#, :controllers => { :registrations => :registrations }
  
  namespace :admin do
    resources :users
    resources :messages
    resources :documents
    get '/financials' => 'documents#financials'
    get '/reports' => 'documents#reports'
    get '/misc' => 'documents#misc'
  end

  root :to => 'site#index'
  match 'user_root' => 'messages#index'
  match '/portal' => 'messages#index', :via => :get
  match '/message/:id' => 'messages#show', :as => :message, :via => :get
  match '/message/:id/hide' => 'messages#hide', :as => :hide_message#, :via => :post
  
  match '/documents' => 'documents#index', :via => :get 
  get '/documents/financials' => 'documents#financials'
  get '/documents/reports' => 'documents#reports'
  get '/documents/misc' => 'documents#misc'
  get '/download/:id' => 'documents#download',:as => :download
end

app/views/shared/_flash.erb
<% if alert %>
    <p class="flash error">
        <%= alert %>
        <a href="#" class="close">&times;</a>
    </p>
<% end %>
<% if notice %>
    <p class="flash notice">
        <%= notice %>
        <a href="#" class="close">&times;</a>
    </p>
<% end %>

app/views/shared/_lightbox.erb
<div class="lightbox">

	<div class="lightbox-inner">
    <div class="modal-close"></div>
		<div class="lightbox-title"><h3></h3></div>
        <div class="lightbox-slide-wrap">
            <!-- slideshow container -->
        	<div class="lightbox-slides" 
            data-cycle-pager=".cycle-pager"
            data-cycle-log="false"
            data-cycle-fx="fadeout"
            data-cycle-pager-template="<a href=#>0{{slideNum}}</a>"
            data-cycle-prev=".cycle-pager-left"
            data-cycle-next=".cycle-pager-right"></div>

            <!-- numbered pager -->
            <div class="cycle-pager"></div>

            <!--  prev/next pager -->
            <span class="cycle-pager-left"></span>
            <span class="cycle-pager-right"></span>
        </div>
    	<div class="lightbox-desc">
            <p></p>
        </div>
    	<a href="javascript:void(0);" style="" class="mobile-close"></a>
  	</div>
    
</div>

app/views/shared/_mobile-bar.erb
<section id="mobile-bar">
  <div class="msg">
  <% if current_user && current_user.admin? %>
    <%= link_to icon_helper('icon-envelope-alt'), admin_messages_path , class: 'menu-item' %>
  <% elsif current_user %>
    <%= link_to icon_helper('icon-envelope-alt') + unread_count, portal_path , class: 'menu-item' %>
  <% else %>
    SOMETHING IS VERY WRONG
  <% end %>
  </div>

  <div class="doc">
  <% if current_user && current_user.admin? %>
    <%= link_to icon_helper('icon-folder-open'), admin_documents_path , class: 'menu-item' %>
  <% else %>
    <%= link_to icon_helper('icon-folder-open'), documents_path , class: 'menu-item' %>
  <% end %>
  </div>

  <div class="sort">
   <div class="sort-content">
      <%= select_year(Date.today, { :start_year => 2013, 
                                     :end_year => Date.today.year}, 
                                  {:class => 'mobile'} ) %>
      <i class=" icon-angle-right"></i>
    </div>
  </div>
  
</section>

app/views/shared/_portal-header.erb
<header role="banner" class="site-header navigation">

 
  <h1 class="mobile-logo" data-slide="1"><a href="/" >AJCP</a></h1>
  <a class="mobile-nav" href="#menu">
    <div class="btn-bar"></div>
    <div class="btn-bar"></div>
    <div class="btn-bar"></div>
  </a>

  <nav id="menu" role="navigation">
    <ul class="navigation">
      <li data-slide="2"><a href="/#portfolio">Portfolio</a></li>
      <li data-slide="3"><a href="/#philosophy">Philosophy</a></li>
      <li data-slide="4"><a href="/#our-team">Team</a></li>
      <li data-slide="5"><a href="/#contact-us">Contact</a></li>
      <li class="login"><%= link_to 'Investor Login', portal_path %></li>
      <% if current_user %>
        <li><%= link_to 'Logout', destroy_user_session_path, class: 'menu-item', method: :delete %></li>
      <% end %>
    </ul>
  </nav>

  
  <nav class="big-header">
    <ul class="header-nav navigation left">
      <li data-slide="2"><a href="/#portfolio">Portfolio</a></li>
      <li data-slide="3"><a href="/#philosophy">Philosophy</a></li>
      <li data-slide="4"><a href="/#our-team">Team</a></li>
    </ul>
    
    <h1 class="" data-slide="1">
      <a href="/">AJ Capital Partners</a>
    </h1>

    <ul class="header-nav navigation right">
      <li class="login"><%= link_to 'Investor Login', portal_path %></li>
      <li data-slide="5"><a href="/#contact-us">Contact</a></li>
    </ul>
  </nav>

  

</header>

app/views/shared/_sidebar.erb
<section id="sidebar">


  <% if current_user && current_user.admin? %>
    <div class="box">
      <%= link_to icon_helper('icon-envelope-alt') + 'Messages', admin_messages_path , class: 'menu-item' %>
    </div>
    <div class="box">
      <%= link_to icon_helper('icon-plus-sign') + 'New Message', new_admin_message_path , class: 'menu-item' %>
    </div>
    <div class="box">
      <%= link_to icon_helper('icon-folder-open') + 'File Archive', admin_documents_path , class: 'menu-item' %>
      <%= link_to split_button_helper('icon-plus') + 'Add File', new_admin_document_path , class: 'split-button' %>            
    </div>
    <div class="box">
      <%= link_to icon_helper('icon-folder-open') + 'Financials', admin_financials_path , class: 'menu-item' %>
      <%= link_to icon_helper('icon-folder-open') + 'Reports', admin_reports_path , class: 'menu-item' %>
      <%= link_to icon_helper('icon-folder-open') + 'Misc.', admin_misc_path , class: 'menu-item' %>
    </div>
  <% elsif current_user %>

    <div class="box">
      <%= link_to icon_helper('icon-envelope-alt') + 'Messages' + unread_count, portal_path , class: 'menu-item' %>
    </div>
    <div class="box">
      <%= link_to icon_helper('icon-folder-open') + 'File Archive', documents_path , class: 'menu-item' %>
    </div>
    <div class="box">
      <%= link_to icon_helper('icon-folder-open') + 'Financials', documents_financials_path , class: 'menu-item' %>
      <%= link_to icon_helper('icon-folder-open') + 'Reports', documents_reports_path , class: 'menu-item' %>
      <%= link_to icon_helper('icon-folder-open') + 'Misc.', documents_misc_path , class: 'menu-item' %>
    </div>
  <% else %>
    SOMETHING IS VERY WRONG
  <% end %>

  <% if current_user && current_user.admin? # Account management links %>
    <div class="box">
        <%= link_to icon_helper('icon-user') + 'Manage Users', admin_users_path , class: 'menu-item' %>
    </div>
  <% end %>  

  <div class="box">
    <%= link_to icon_helper('icon-wrench') + 'Edit Account', edit_user_registration_path , class: 'menu-item' %>
    <%= link_to icon_helper('icon-signout') +'Logout', destroy_user_session_path, class: 'menu-item', method: :delete %>
  </div>

</section>

app/views/shared/_site-footer.erb
<footer class="site-footer">
  <article class="inner">
        <div class="site-info">&copy; <%= copyright_year %> AJ Capital Partners. All rights reserved.</div>
        <nav class="footer-nav">
          <ul class="navigation">
            <!-- TODO: replace with Rails links -->
            <li data-slide="2"><a href="#portfolio">Portfolio</a></li>
            <li data-slide="3"><a href="#philosophy">Philosophy</a></li>
            <li data-slide="4"><a href="#our-team">Team</a></li>
            <li class="login"><%= link_to 'Investor Login', portal_path %></li>
            <li data-slide="5"><a href="#contact-us">Contact</a></li>
          </ul>
        </nav>
    </article>
</footer> 

app/views/shared/_site-header.erb
<header role="banner" class="site-header navigation">

 
  <h1 class="mobile-logo" data-slide="1"><a href="/" >AJCP</a></h1>
  <a class="mobile-nav" href="#menu">
    <div class="btn-bar"></div>
    <div class="btn-bar"></div>
    <div class="btn-bar"></div>
  </a>

  <nav id="menu" role="navigation">
    <ul class="navigation">
      <li data-slide="2"><a href="#portfolio">Portfolio</a></li>
      <li data-slide="3"><a href="#philosophy">Philosophy</a></li>
      <li data-slide="4"><a href="#our-team">Team</a></li>
      <li data-slide="5"><a href="#contact-us">Contact</a></li>
      <li class="login"><%= link_to 'Investor Login', portal_path %></li>
      <% if current_user %>
        <li><%= link_to 'Logout', destroy_user_session_path, class: 'menu-item', method: :delete %></li>
      <% end %>
    </ul>
  </nav>

  
  <nav class="big-header">
    <ul class="header-nav navigation left">
      <li data-slide="2"><a href="#portfolio">Portfolio</a></li>
      <li data-slide="3"><a href="#philosophy">Philosophy</a></li>
      <li data-slide="4"><a href="#our-team">Team</a></li>
    </ul>
    
    <h1 class="" data-slide="1">
      <a href="/">AJ Capital Partners</a>
    </h1>

    <ul class="header-nav navigation right">
      <li class="login"><%= link_to 'Investor Login', portal_path %></li>
      <li data-slide="5"><a href="#contact-us">Contact</a></li>
    </ul>
  </nav>

  

</header>