config/routes.rb
AjCapital::Application.routes.draw do

  devise_for :users#, :controllers => { :registrations => :registrations }
  
  namespace :admin do
    resources :users
    resources :messages
    resources :documents
    get '/financials' => 'documents#financials'
    get '/reports' => 'documents#reports'
    get '/misc' => 'documents#misc'
  end

  root :to => 'site#index'
  match 'user_root' => 'messages#index'
  match '/portal' => 'messages#index', :via => :get
  match '/message/:id' => 'messages#show', :as => :message, :via => :get
  match '/message/:id/hide' => 'messages#hide', :as => :hide_message#, :via => :post
  
  match '/documents' => 'documents#index', :via => :get 
  get '/documents/financials' => 'documents#financials'
  get '/documents/reports' => 'documents#reports'
  get '/documents/misc' => 'documents#misc'
  get '/download/:id' => 'documents#download',:as => :download
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many  :messages,
              :as => :sender,
              :class_name => 'Message',
              :conditions => {:hidden_at => nil},
              :order => 'messages.created_at DESC'
              
  has_many  :received_messages,
              :as => :receiver,
              :class_name => 'MessageRecipient',
              :include => :message,
              :conditions => ['message_recipients.hidden_at IS NULL AND messages.state = ?', 'sent'],
              :order => 'messages.created_at DESC'

  attr_accessible :email, :username, :password, :password_confirmation, :remember_me, :is_admin
  attr_accessor :is_admin

  validates :email,    :presence => true, :uniqueness => true
  validates :username, :presence => true
  validates :password, :presence => true, :on => :create

  before_save :update_role_if_applicable

  def admin?
    has_role? :admin
  end

  def unsent_messages
    messages.with_state(:unsent)
  end

  def sent_messages
    messages.with_states(:queued, :sent)
  end

  def unread_messages_count
    # MessageRecipient.
    #   joins(:message).
    #   where(
    #     :receiver_id => self.id, 
    #     :receiver_type => 'User', 
    #     :hidden_at => nil,
    #     'messages.state' => 'unread').
    #   count
    self.received_messages.where(state:'unread').count
  end

  def documents
    
  end

  private

    def update_role_if_applicable 
      return unless is_admin.present?

      remove_role :admin if admin? && is_admin == '0'
      add_role :admin    if !admin? && is_admin == '1'  
    end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #   IMPORTANT NOTE!
  # 
  #   The `load_and_authorize_resource` method automagically creates the instance 
  #   for each method below.
  # 
  #   They remain in place but commented out for the sake of being explicit
  # 
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  load_and_authorize_resource
  
  layout 'portal'

  def index
    # @users = User.all  
    @users = @users.page(params[:page]).per(PER_PAGE)
  end

  def show
    # @user = User.find(params[:id])
  end

  def edit
    # @user = User.find(params[:id])
  end

  def update
    fields = params[:user]
    
    @user.is_admin   = fields.delete(:admin)
    @user.attributes = fields
    

    if @user.save
      redirect_to admin_users_path, notice: 'User was successfully updated.'
    else
      render action: 'edit', notice: 'Something when wrong with the record update'
    end

  end

  def new
    # @user = User.new
  end

  def create
    if @user.save
      redirect_to admin_user_path @user, notice: 'User was successfully created.'
    else
      render action: 'new'
    end
    
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: 'User was successfully deleted.'
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/user_helper.rb
module UserHelper

  def user_admin(user)
    '<i style="font-style: italic; color:red;">admin</i>'.html_safe if user.admin?
  end

  def user_name(user)
    icon = user.admin? ? 'icon-user-md' : 'icon-user'
    icon_helper(icon) + " #{user.username}"
  end

end

app/views/admin/users/edit.html.erb
<% title 'Edit User' %>
<section id="user-index">
  <header>
    <div class="content">
        Edit User
        <span class="right">
          <%= link_to icon_helper('icon-plus') + '&nbsp;&nbsp;Create User'.html_safe , new_admin_user_path, :class => 'button create' %> 
        </span
    </div>
  </header>

  <%= simple_form_for [:admin, @user] do |f| %>
    <%= f.input :username, :required => false %>
    <%= f.input :email %>
    <%= f.input :admin?, :label => "Admin permissions", :as => :boolean %>
    <%= f.button :submit %>
  <% end %>

</section>

app/views/admin/users/index.html.erb
<% title 'Manage Users' %>
<section id="user-index">
  <header>
    <div class="content">
        Manage Users
        <span class="right">
           <%= link_to icon_helper('icon-plus') + '&nbsp;&nbsp;Create User'.html_safe , new_admin_user_path, :class => 'button create' %>
        </span>
       
    </div>
  </header>

  <ul class="users">
    <% @users.each do |user| %>
      <li class="user" id="user-<%= user.id %> ">
        <ul>
            <li class="user-name"><%= user_name(user) %></li>
            <li class="user-email"><%= user.email %></li>
            <li class="user-admin"><%= user_admin(user) %> </li>
            <li class="user-controls">
                <%= link_to icon_helper('icon-edit') , edit_admin_user_path(user), class: 'button edit'%>
                <%= link_to icon_helper('icon-remove') , admin_user_path(user), class: 'button delete', method: :delete, data: { confirm: 'Are you sure?' } %>
            </li>
        </ul>
      </li>
     <% end %>
  </ul>
  
  <%= paginate @users %>

</section>

app/views/admin/users/new.html.erb
<% title 'New User' %>
<section id="user-new">
  <header>
    <div class="content">
        New User
    </div>
  </header>

  <%= simple_form_for [:admin, @user] do |f| %>
    <%= f.input :username, :required => false %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>

    <%= f.button :submit %>
  <% end %>

</section>

app/views/admin/users/show.html.erb
<section id="user-detail">

  <header>
    <div class="content">
      User Detail
    </div>
  </header>

  <div class="user">
    <span class="user-email">Username: <%= @user.username %></span>
    <span class="user-email">Email: <%= @user.email %></span>
  </div>

</section>